### ISSUE TITLE
String and pattern matching 

### ISSUE THREAD

**Issue by kenmcgarry** [JBGruber/highlightr#1]
Hi,

I find your package very useful for highlighting patterns in a text string but would like to be able to see/use the internal functions that identify the patterns to be highlighted and to give some sort of indication [index] where they are on the string. 

Thanks
Ken

**Comment by JBGruber** [comment]
Hi Ken,

This is not how the package works, I'm afraid. The features are replaced in text with the feature wrapped in the syntax to change the output. So if you want to highlight "word" by italising it in an html doc, the underlying functions replace it with `<em>word</em>` without returning information on where the word is.

What you are describing can be done with `str_locate` from `stringr` or the `stri_locate_*` functions in `stringi` though. 

Best
Johannes
